name: my_check_in
on:
  schedule:
  - cron: 0 22 * * *
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    environment: push
    steps:
      - name: Detection Code
        uses: actions/checkout@v4
      
      - name: Caching Python Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log/debug.log
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-100 -n 1)
          
      - name: Run checkin
        run: |
          python3 ./main.py --token_string "${{ secrets.TOKEN }}"
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVERCHAN_SENDKEY: ${{ secrets.SCKEY }}
          WECOM_TOKENS: ${{ secrets.WECOM_TOKENS }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
          FEISHU_DEVICEKEY: ${{ secrets.FEISHU_DEVICEKEY }}
          EMAIL: ${{ secrets.EMAIL }}
          IKUUU_PASSWD: ${{ secrets.IKUUU_PASSWD }}
      -  uses: stefanzweifel/git-auto-commit-action@v5
      - uses: gautamkrishnar/keepalive-workflow@master
